#!/usr/bin/env bash
# coverage.sh — Build with coverage instrumentation and generate an HTML report.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${REPO_ROOT}/build/coverage"
REPORT_DIR="${BUILD_DIR}/coverage-report"

cmake --preset coverage -S "${REPO_ROOT}" -B "${BUILD_DIR}"
cmake --build "${BUILD_DIR}" -j

mkdir -p "${REPORT_DIR}"

test_count="$(ctest --test-dir "${BUILD_DIR}" -N | awk '/Total Tests:/ { print $3 }')"
test_count="${test_count:-0}"

if [[ "${test_count}" -eq 0 ]]; then
        echo "No tests are registered for the coverage preset. Skipping lcov capture."
        cat > "${REPORT_DIR}/index.html" <<'EOF'
<!doctype html>
<html lang="en">
        <head>
                <meta charset="utf-8">
                <title>Xuanjing SDK Coverage</title>
        </head>
        <body>
                <h1>Coverage report unavailable</h1>
                <p>No tests are currently registered, so no runtime coverage data was produced.</p>
        </body>
</html>
EOF
        echo "Report: ${REPORT_DIR}/index.html"
        exit 0
fi

ctest --test-dir "${BUILD_DIR}" --output-on-failure

if ! find "${BUILD_DIR}" -name '*.gcda' -print -quit | grep -q .; then
        echo "No .gcda files were generated by the coverage run. Writing a placeholder report."
        cat > "${REPORT_DIR}/index.html" <<'EOF'
<!doctype html>
<html lang="en">
        <head>
                <meta charset="utf-8">
                <title>Xuanjing SDK Coverage</title>
        </head>
        <body>
                <h1>Coverage report unavailable</h1>
                <p>Tests ran, but no coverage data files were generated for this build.</p>
        </body>
</html>
EOF
        echo "Report: ${REPORT_DIR}/index.html"
        exit 0
fi

lcov --capture \
     --directory "${BUILD_DIR}" \
     --output-file "${BUILD_DIR}/coverage.info" \
     --exclude "*_stub.cpp" \
     --exclude "*/tests/*"

genhtml "${BUILD_DIR}/coverage.info" \
                                --output-directory "${REPORT_DIR}"

echo "Report: ${REPORT_DIR}/index.html"
